CREATE TABLE Users (
User_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
User_Token VARCHAR(32) NOT NULL,
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE (User_Token)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE Events (
Event_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Event_Token INT UNSIGNED NOT NULL,
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE(Event_Token)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE User_Events (
User_ID INT UNSIGNED NOT NULL,
Event_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (User_ID) REFERENCES Users(User_ID),
FOREIGN KEY (Event_ID) REFERENCES Events(Event_ID),
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE (User_ID, Event_ID)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE Properties (
Property_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Property_Name VARCHAR(64) NOT NULL,
Property_Value VARCHAR(64),
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE(Property_Name)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE Logins (
Login_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Login_Name VARCHAR(64) NOT NULL,
Login_Key VARCHAR(64) NOT NULL,
Enabled BIT NOT NULL DEFAULT 1,
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE(Login_Name)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE Versions (
Version_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Version_Code VARCHAR(32) NOT NULL,
Version_Code_Decimal DECIMAL(10,2) NOT NULL,
Version_Description TEXT NOT NULL,
Version_Changes TEXT NOT NULL,
Pre_Release TINYINT(1) NOT NULL,
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE(Version_Code)
)ENGINE=InnoDB CHARACTER SET UTF8;

CREATE TABLE Groups (
Group_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Group_Token INT UNSIGNED NOT NULL,
Last_Update_Datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE(Group_Token)
)ENGINE=InnoDB CHARACTER SET UTF8;

INSERT INTO Properties(Property_Name, Property_Value) VALUES('mtime', NULL)